### ISSUE TITLE
Travis integration

### ISSUE THREAD

**Issue by szepeviktor** [WordPress-Coding-Standards/WordPress-Coding-Standards#712]
Please consider adding TravisCI integration documentation in the readme.
Thank you.

**Comment by jrfnl** [comment]
PR opened #753 - your feedback is welcome.

**Comment by szepeviktor** [comment]
Thank you!

So no composer will be suggested?

```yaml
before_script:
  - composer require --dev wp-coding-standards/wpcs
  - vendor/bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs/
script:
  - vendor/bin/phpcs -p --standard=WordPress .
```
